### ISSUE TITLE
Create basis (system) schema

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#10]
Directus has a few system-records in the DB to operate properly. Think of records like system relations (files-folders).

We need to include an SQL file that can be used during installation so the DB is setup correctly.

We also need to make sure this file can be used when you already have data in your database. (When you move your existing dataset to directus)

This needs to wait a bit till we have finalized the api / app integration.

**Comment by rijkvanzanten** [comment]
I think we should wait on this. The demo DB gets filled piece by piece during development. When that's in a state we're happy with, we can extract the rows that are in there to create the basis schema.

**Comment by rijkvanzanten** [comment]
[directus_2018-04-24.sql.zip](https://github.com/directus/api/files/1947425/directus_2018-04-24.sql.zip)

🎉

**Comment by WellingGuzman** [comment]
- The `revisions.item` and `revisions.parent_item` have `textinput` as interface (the rest are called `text-input`), which I assumed is a typo and replaced it with `text-input`.

- There’s missing field information (which we already have from previous schema so we are good there, but had to noted it. ex `users.roles`).

- The `SORT` and `STATUS` type doesn’t exists yet, so I changed it for `INT` until we implement them.

- I used `JSON` type instead of `TEXT` where the interface is `json`.

- Set `create`, `read`, `update`, `delete`, `explain`, and `navigate`  were changed from `int` to `boolean`.

- `users.status` has not status mapping, I set options to (from previous schema):

```
{
   "status_mapping":[
      {
         "name":"draft"
      },
      {
         "name":"active"
      },
      {
         "name":"delete"
      }
   ]
}
```

**Comment by WellingGuzman** [comment]
Schema updated by https://github.com/directus/api/commit/de8016e7736a0e5caaa6e5c88e6a125170e3ac69

**Comment by benhaynes** [comment]
> Set create, read, update, delete, explain, and navigate were changed from int to boolean.
 Is this right? I think it would be best to change the saved values for permissions to:
`none` (or `NULL`), `user`, `group`, `all`... this might make more sense than just `0`, `1`, `2`, `3`

Thoughts? @WellingGuzman @rijkvanzanten

**Comment by rijkvanzanten** [comment]
@benhaynes is right. Those fields aren't Boolean, since they can have multiple options. For those multiple options, it's clearer to use strings than to use numbers.

**Comment by WellingGuzman** [comment]
> Is this right? I think it would be best to change the saved values for permissions to:
none (or NULL), user, group, all... this might make more sense than just 0, 1, 2, 3

Oh true, that's right. those aren't boolean.

Another thing we can map those values and represent them as string in the app.

**Comment by rijkvanzanten** [comment]
Lets keep them as strings @WellingGuzman. If we're using numbers, developers would have to search in the docs for the "translations" from number to string to find out what 1 means. It's more clear for devs if it just returns the human readable permissions 🙂
