### ISSUE TITLE
Files permission 'mine' not working

### ISSUE THREAD

**Issue by phoenixtechnam** [directus/api#1044]
# Possible Bug Report
I am trying to achieve full api data separation based on user accounts. That works well so far by setting access permissions to 'mine' for custom collections and non-admin users.
Now I want users to see 'their' files only. Using the 'mine' permission on directus-files doesn't work as expected.
How can I achieve file access rights separation based on user accounts?

## Steps to Reproduce
0. Login as non-admin user and upload a file
1. Go to SQL database
2. set the appropriate user group permissions to 'mine' for directus-files 
3. APP does not show any files, server error for non-admin users
4. JS SDK cannot retrieve files although **login user** and **uploaded_by** user are the same.

## Expected Behavior
User should only see files uploaded by themselves

## Actual Behavior
User does not see any files.

## Technical Details
- Device: vServer
- OS: CentOs 7
- Web Server: Apache+Nginx
- PHP Version: 7.3
- Database: MariaDB
- Install Method: cloned `master` branch

**Comment by bjgajjar** [comment]
Hello @phoenixtechnam 

You have updated `mine` permission from direct DB. For a `mine` permission we need a `user-created` field. `directus-files` collection have not any `user-created` field. That's why we didn't provide the `mine` permission for `directus-files` collection at `APP` side,

`uploaded-by` field is a `user` field, not a `user-created`. So you are not getting the expected response. 

I am closing this request; If you require the `mine` permission in `directus-files` collection, please add it as **Feature-Request.**

**Comment by dev7ch** [comment]
@bjgajjar i just read the thread here and saw we have `uploaded_by` field in directus_files table, this equivalent to `user-created` field, isn`t?

**Comment by phoenixtechnam** [comment]
It used not to work this way but APP v8 now allows to set the MINE permission on directus_files and it seems to work as expected now.
