### ISSUE TITLE
O2M not honoring "Required Field" check

### ISSUE THREAD

**Issue by benhaynes** [directus/api#1114]
# Bug Report

## Steps to Reproduce

1. Make a O2M field `requires
2. Leave the interface values blank or delete all items
3. Try to save
4. It saves

## Expected Behavior

It should return an error that field XXXX: Is required like other fields do. 

## Actual Behavior

It saves without performing the check since there is technically data in the field's request.

I know this is really complex since we need to do a check if any items will remain AFTER the request is processed. Yikes! Any ideas @directus/api-team ?

**Comment by bjgajjar** [comment]
Hey @rijkvanzanten,

It seems like the payload for delete `M2O` field from `O2M` collection have been changed.

- Previously, we have `$delete` flag to remove it from `O2M` collection.
   `{ "card": [{ "id" : 4, "$delete":true }] }`

- Now, we have a `null` as an `M2O` field.
  `{ "card": [{ "id" : 4, "section":null }] }`

Let me mention here that payload for `M2M` has not been changed. This applied only on `O2M` collection.

So may I have a confirmation for the payload of both `M2M` and `O2M`? 

1. Will these both worked on `$delete` flag only? (Need to revert for `O2M` from `APP` side)
2. The current structure seems okay. `O2M` will work with `null` value and `M2M` will have `$delete` flag.

Let me know which option need to be considered, so I can start the work :)

**Comment by rijkvanzanten** [comment]
@bjgajjar both are available (it's an interface option). 

@benhaynes already knew this but didn't mention in the post above (besides "I know this is really complex"):

The problem here is the fact that from a user-perspective, an empty value for O2M shouldn't pass the required state. One can set the O2M to be empty by nullifying the related items (like example 2). After this update is done, the O2M is in a `null` value state, which should cause the `required` check to kick in.

The difficulty here lies in the fact that the API will have to check if the O2M will have any related items _after_ performing all the updates before actually performing the updates in order to be able to retrieve the actual field value.

---

`$delete: true` will delete the related item (either the 'many' side in a o2m or the junction record in a m2m. You might not want to delete the related item, which is why you might send `section: null` instead. Both are valid options.

As of right now, only O2M has the option to use the second version, as a junction row is often times more tightly coupled to the m2m. However, it's entirely possible that this option will make it's way into the m2m interface as well. (Which should be totally fine, as the m2m is nothing different from a regular o2m as far as the API is concerned. If it works for o2m, it works for m2m).

**Comment by bjgajjar** [comment]
>both are available (it's an interface option).

Thanks for the info. I didn't know that. 

> The difficulty here lies in the fact that the API will have to check if the O2M will have any related items _after_ performing all the updates before actually performing the updates in order to be able to retrieve the actual field value.

I am aware of it. 

My only concern was, am I supposed to provide the support for `null` as well as `$delete` for removing data or not? But if the interface has these both option, then I have to provide it. :)

**Comment by rijkvanzanten** [comment]
It's not just about the interface though. The user can also do this directly in the API, as there is no way to nullify the relationship otherwise 🙂

**Comment by bjgajjar** [comment]
Fixed in #1128
