### ISSUE TITLE
M2M field is not visible for reverse relation.

### ISSUE THREAD

**Issue by bjgajjar** [directus/api#1132]
# Feature Request
`category` collection has `M2M` field for `files` collection. The listing API returns the `file` object for `category` collection, but will not return the `category` object for `files` collection.

## What problem does this feature solve?
`files` collection must have the `category` object too.

**Comment by benhaynes** [comment]
Thoughts on this @rijkvanzanten ?

Some users might not want that field/data in the opposite direction... but I agree that we should make it easy to include it (if the user wants it) when setting up the initial field. Perhaps a `Create Reverse Field on Related Collection` option when setting up the relation?

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
> but will not return the category object for files collection.

This is because there isn't a m2m alias field on directus_files for category, which makes sense.

We can't infer the name of this alias field on the "other side" and probably shouldn't try to automatically generate it either (eg `files -> categories` should have a `file` on `categories` and `category` on `files`, there's no way to accurately generate all of this singular forms + i18n).

Second problem: what happens if you have multiple m2m's to files? It's very common to have multiple m2m's (multiple files) to directus_files. Should the API automatically inject all of this related data in calls to directus_files? I don't think so.

Downvote from me!

**Comment by benhaynes** [comment]
I understood this a bit differently. I agree that we shouldn't have any _automatic_ reverse relational data... but having an easier way to add the reverse field _is_ quite useful. Given this direction...

> what happens if you have multiple m2m's to files? 
You would have multiple M2M fields added on the related collections (`files` in this case).

I see this as an App feature that would let the user easily setup a M2M in _both_ directions.

**Comment by rijkvanzanten** [comment]
Yet this is a feature request on the API, I'm fine with what you're proposing as a UX improvement in _the application_, but I'm still downvoting this as an API feature

**Comment by benhaynes** [comment]
Agreed.
