### ISSUE TITLE
Create new error code for invalid login entity

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#1186]
When the user logs in through `/auth/authenticate` with an invalid email address, the API returns with an error code `4` with a message of `email: This value is not a valid email address.`. 

Authentication errors are all scoped in the `100` range, except for the 422 error on auth. Should we add a `0109` error code for the "Invalid email provided" error?

Ref: https://github.com/directus/app/issues/1801

**Comment by shealavington** [comment]
Theoretically when logging in, you should never see "Email is invalid" or "Password is invalid", however, "Email or Password is invalid" would be okay imo.

**Comment by rijkvanzanten** [comment]
That's already the case @shealavington. This error is not for "wrong username/password" this is for invalid payloads eg an email that's "rijk#rngr.org" or a password that's empty.

**Comment by hemratna** [comment]
To clarify,

1. `4XX` (like `422`) are HTTP STATUS code
2. `100` (like Authentication errors, and other errors) are [Directus defined error code ](https://docs.directus.io/api/reference.html#error-codes)

To make more cleaner error code, as @WoLfulus suggested on #1104 
Instead of using numbered error code (like `0100`, `0101`) we can use the text (like `EMAIL_NOT_FOUNT`, `INVALID_TOKEN`)

And along with text error code, we also supply the appropriate HTTP STATUS code.

Additionally, we can create one endpoint (like `GET /errors`) to list out all the possible error code along with messages. So App can use that endpoint and display user-friendly error msg.

**Comment by rijkvanzanten** [comment]
I like the idea of using string based error codes, but that doesn't negate this original request 😉 

> Additionally, we can create one endpoint (like GET /errors) to list out all the possible error code along with messages. So App can use that endpoint and display user-friendly error msg.

I think we don't need this, all the error codes will have a description in the languages files in the Directus app itself. The API doesn't have any localization, so those strings won't be used most likely

**Comment by hemratna** [comment]
Fixed in #1218
