### ISSUE TITLE
divider on child collection  prevents creating new items 

### ISSUE THREAD

**Issue by markus-mnm** [directus/api#1227]
# Bug Report

This happens with APP 7.10.0 and API 2.5.0 both on local as well as https://directus.app

When a child collection has a divider, it prevents creating the new item because it tries to insert the divider as a column

## Steps to Reproduce

Create a collection demo_articles and a collection demo_articles_sections (some fields removed for simplicity):

```
demo_articles_sections
      id
      parent_id
      text
      separator

demo_articles
     id
     sections (O2M)
   
```
creating a new demo_articles item with a new demo_articles_sections item  results in:
```
{"error":{"code":9,"message":"Failed generating the SQL query. Statement could not be executed (42S22 - 1054 - Unknown column 'separator2' in 'field list')","query":"INSERT INTO `demo_articles_sections` (`label`, `display_order`, `photo`, `photo_credit`, `layout_details`, `created_by`, `created_on`, `modified_by`, `modified_on`, `separator2`, `parent_id`) VALUES ('section 4', '99', NULL, NULL, NULL, '15', '2019-08-28 15:11:41', '15', '2019-08-28 15:11:41', NULL, '1')","class":"Directus\\Database\\Exception\\InvalidQueryException","file":"\/var\/www\/html\/src\/core\/Directus\/Database\/TableGateway\/BaseTableGateway.php","line":815}}<br />
````

On https://directus.app/ the error is:

    error: {code: 9, message: "Failed generating the SQL query.",…}
    code: 9
    message: "Failed generating the SQL query."
    query: "INSERT INTO `demo_articles_sections` (`created_by`, `created_on`, `text`, 
       `separator1`, `parent_id`) VALUES ('1', '2019-08-28 18:22:19', 'test', NULL, '4')"

## Expected Behavior

the divider is ignored

## Actual Behavior

the divider is being "inserted" and fails

**Comment by bjgajjar** [comment]
Fixed in #1240

**Comment by mutor-gmbh** [comment]
Although the issue above was fixed in v2.6.0, Alias fields in the form of dividers can still cause problems in the latest version (v2.6.0).

# Steps to reproduce #
- Create a collection with a divider
- Create a new entry in that collection
- Open the newly created entry
- Try to modify it and then save it

# Expected Behavior #
Entry should be updated

# Actual Behavior #
API returns invalid JSON

```
"{"data":{"id":1,"test":"test3"}}<br />
<b>Notice</b>:  Undefined index: divider in <b>/var/www/directus/src/core/Directus/Services/ItemsService.php</b> on line <b>176</b><br />
"
```

**Comment by christianrr** [comment]
Although the issue above was fixed in v2.6.0, Alias fields in the form of dividers can still cause problems in the latest version (v2.6.0).

# Steps to reproduce #
- Create a collection with a divider
- Create a new entry in that collection
- Open the newly created entry
- Try to modify it and then save it

# Expected Behavior #
Entry should be updated

# Actual Behavior #
API returns invalid JSON

```
"{"data":{"id":1,"test":"test3"}}<br />
<b>Notice</b>:  Undefined index: divider in <b>/var/www/directus/src/core/Directus/Services/ItemsService.php</b> on line <b>176</b><br />
```

**Comment by bjgajjar** [comment]
@christianrr - https://github.com/directus/api/issues/1330 may be this what you are talking about.
 :)

**Comment by christianrr** [comment]
> @christianrr - #1330 may be this what you are talking about.
> :)

Indeed ;) thanks
