### ISSUE TITLE
Auth token is not refreshed

### ISSUE THREAD

**Issue by bijanmj** [directus/api#1232]
The app gets disconnected every 5 minutes and I have to log back in again. The token refresh endpoint is never hit.
Here's what I have in sessionStorage:
```
{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTY2NTA4NDk3LCJ0eXBlIjoiYXV0aCIsImtleSI6Ijx0eXBlLWEtcHVibGljLWF1dGhlbnRpY2F0aW9uLWtleS1zdHJpbmc-IiwicHJvamVjdCI6Il8ifQ.2SKSsDZ8WszHVZ92bcBzsig0WTaeu8weVsFXkepdZa4","url":"http://api.admin.dbrs.biz:5000","project":"_","localExp":1566509408586}
```

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1233

**Comment by ErwinLiemburg** [comment]
I hoped this issue was fixed in 2.6.0, but unfortunately the problem still occurs. I'm using e-mail/password for login.

For example, after logging in the token `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTY5MzQ1OTUwLCJ0eXBlIjoiYXV0aCIsImtleSI6ImFmMTI2NzM0LTFmZWMtNGI1OC05ZDNkLWUxNDZmZjgwZWRmMiIsInByb2plY3QiOiJfIn0.wDX9_kOpRGXnDr97YW5JxEU92QjSUtacXGZf9L0WLiY` was received. 

Decrypting it results the following payload:
`{
 "id": 1,
 "exp": 1569351022,
 "type": "auth",
 "key": "af126734-1fec-4b58-9d3d-e146ff80edf2",
 "project": "_",
 "jti": "50702ce6-c11c-46c9-9e64-2612c307fd61",
 "iat": 1569347422
}`

After a while when the App refreshes I receive the token: `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.Im51bGwi.pdKuwHJ7M2IqJfksDypw-C2NtCS8juuY8Lqgts59DF4`

Decripting this results in the payload:
`{
 "0": "n",
 "1": "u",
 "2": "l",
 "3": "l"
}`

This means that after the first refresh I have to login again. The App refreshes after 20 minutes, but the SDK-js, by default, refreshes after 5 minutes. It's annoying. Hope this can be fixed.

**Comment by benhaynes** [comment]
Hey @ErwinLiemburg — we have an entire new auth flow that resolves this issue and several others. It also adds the ability to stay logged in for any amount of time. It will be released in our next version in about 2 weeks.

**Comment by ErwinLiemburg** [comment]
@benhaynes That sounds great. Can't wait to get it.
