### ISSUE TITLE
Add new fields to / endpoint

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#1329]
# Feature Request

For the new login page, we'd like to have additional fields for images we can use. Currently we have `project_name` and `project_logo`. We should add `project_icon`, `project_color`, and `project_image`.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/9141017/65917347-27e5ee80-e3a5-11e9-82c2-4e96d25c39ac.png">

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1332

**Comment by benhaynes** [comment]
Hey @bjgajjar — I just saw that you are "renaming" the `logo` to `project_logo` on the `/` endpoint, but we want to write migrations to rename the actual field. That way this is set to `project_logo` in the database too (and the label on the App Settings). Can we make that change?

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1389

**Comment by arboehme** [comment]
> Fixed in #1389

Hi,

unfortunately the fix don't work on the new installation, because the seeder already creates entries for `project_foreground` and `project_background` in the `directus_settings` table, so the renaming of the old fields in the schema upgrade results in the constraint violation exception.

I've fixed this in the https://github.com/directus/api/pull/1391, please check it.

Thanks ans best regards

**Comment by bjgajjar** [comment]
Hey @arboehme  - Thanks for reporting the issue as well as send the PR ❤️ 

It was a known issue and we already put that in our queue. But thank you so much for making it easy for us with sending PR. We appreciate it.

I'll review it ASAP :)
