### ISSUE TITLE
Couldn't Reach API in Login page

### ISSUE THREAD

**Issue by JbalTero** [directus/api#1361]
## Steps to Reproduce

- Fresh install of latest develop https://github.com/directus/api/commit/82e06ab90fa38869da141f578922b66b0f645669
- Login
- Logout

## Expected Behavior

There should be no error

## Actual Behavior

`Couldn't Reach API`

## Other Context & Screenshots

[This is what happens in action](https://drive.google.com/file/d/1wPE2LCpIS9e59kft5aXSjK1vpoMj-Ar-/view?usp=sharing)

[Here's the root cause](https://drive.google.com/file/d/1Zzw9lQ-mu92EDWGFSZKGbZoJrbb97YTf/view?usp=sharing). This will be fixed if the session cookie is purged after logout

## Technical Details

- Device: Desktop
- OS: Win 10  10.0.18362.145
- Web Server: Apache/2.4.29
- PHP Version: PHP 7.2.23
- Database: 10.2.26

**Comment by bjgajjar** [comment]
After talking with @JbalTero, able to find out that he used the `develop` branch in `Directus Suite`.

Thus, his `API` code of new Auth flow is there but used the `master` branch of `APP`.
Auth module is in the progress at the `APP` side.

The issue is; `PHPSESSID` is not being destroyed after logging out. 

When we have the Auth module in the `APP` side; it will be not the case. After logout; `APP` will destroy all the cookies from the browser. Although the authentication cookie will not be sent in response header from `API` but this `PHPSESSID` must be removed from `APP` only.
So, you'll not get this error once the Auth module of `APP` is ready.

PS. Try to not use the `dev` branch of `APP` or `API` directly. It may the dependency like this and you may not aware of it. So kindly use the build branch separately from the individual `APP` and `API`.
