### ISSUE TITLE
Activity IP Address

### ISSUE THREAD

**Issue by benhaynes** [directus/api#1475]
Right now we're showing the IP address as `::1`, which I assume is localhost. This looks weird and  doesn't provide much info. Let's instead save `localhost` for these local IP ranges (unless there's something more descriptive we can save).

Also, please make sure that activity is sorted by `Action On — DESC` by default. Mine seemed to be sorted by `id ASC` which is not very useful.

**Comment by bjgajjar** [comment]
@rijkvanzanten - As per mentioned  [here](https://github.com/directus/api/pull/1492#issuecomment-564590465); APP handled it. But it seems like still `directus_activity` table has an IP address instead of `localhost`. 

https://github.com/directus/api/pull/1587 will add this condition at the `API` side too.

Please have a look and provide your feedback.
