### ISSUE TITLE
One of my tables is completly unusable from directUs

### ISSUE THREAD

**Issue by MrKyHn1** [directus/api#1543]
# Bug Report
One of my tables appears completly empty from directUs but it is filled in phpmyadmin
## Steps to Reproduce
It just happened abruptly
1. Go to 'Collections'
2. Click on 'the  table'
3. Scroll down to '...'
the error says "the current filters do not match any collection items" but there are no filters enabled in field search
## Expected Behavior
display of all data from the table (as its content in phpmyadmin)
## Actual Behavior
![bug_emptytable](https://user-images.githubusercontent.com/56399506/70605617-246bb080-1bfb-11ea-87a7-76022b78915d.PNG)

## Other Context & Screenshots
Items added from directus appear for quickly then dissapear definitively( altough they are added to the table when i check phpmyadmin)

## Technical Details

- Device: Desktop
- OS: Windows10
- Web Server: Apache 2.4.25 debian server
- PHP Version: 7.3.11-1
- Database: 5.7.28 - MySQL Community Server (GPL)
- Install Method: wget of git version

**Comment by benhaynes** [comment]
Hey @MrKyHn1 — thanks for reporting this. We'll need a bit more info to see what's happening, as this is almost certainly due to something in the schema/data of your collection (database table). Would you be able to post your table structure or database dump here (or on Slack if it's private)? Some other thoughts:

* Do you have a status field in this collection? That seems like the most likely cause.
* Are you logged in as an Admin? If not, what permissions are you using?
* Can you confirm that this collection is "managed" in Settings?
* What kind of PK are you using? Named `id`? Auto-incrementing `INT`?
* If you open up the "Item Sidebar" on the right, do you see your fields listed there?
* What do you see when you view this collection through Settings>Collections & Fields?

We'll need a dump or some of the answers above to properly troubleshoot this. 👍

**Comment by MrKyHn1** [comment]
1. i don't have a status field in this collection.
2. Yes it's the administrator role, i have evry right and it hasn't been modified.
3.The collection is indeed "managed" (turning off and back on doesn't work)
4.Yes every table has an autoIncrement(int) id as primary key
5. Yes column names are indeed listed.
6. this is what i see from settings.
![bug_emptytable2](https://user-images.githubusercontent.com/56399506/70701088-0f128700-1ccc-11ea-8062-fab460bf73f3.PNG)
(the only thing remaining after that is the icon adding menu)

**Comment by benhaynes** [comment]
My guess is that it's because you're using the `numeric` interface instead of the `primary key` interface.

**Comment by MrKyHn1** [comment]
It says numeric here but look the detailed settings of the field:
![bugfix institution](https://user-images.githubusercontent.com/56399506/70719237-eac9a100-1cf1-11ea-9340-881f5b78260f.PNG)

**Comment by MrKyHn1** [comment]
I changed it from numeric to primary key and it still is the same:
![bugfix institution](https://user-images.githubusercontent.com/56399506/70719567-89560200-1cf2-11ea-9472-ae64ed0f61c3.PNG)

**Comment by benhaynes** [comment]
Then I'm out of ideas with the info provided. If you can provide a database dump (here, or privately over Slack) then we can troubleshoot further.

https://directus.chat

**Comment by benhaynes** [comment]
After speaking with @MrKyHn1 over Slack and seeing their schema, it appears they had incorrectly setup a relationship to this `institution` collection from a different collection (`user`). The broken relationship was causing an error when trying to fetch the data.
