### ISSUE TITLE
API requires PHP_SESSID to be present / correct

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#1563]
In bigger (enterprise) Directus installations, it's common to have multiple instances of Directus connected to the same database, with a load balancer in front to send people to the different instances based on usage. The Directus application relies on Cookies for its authentication, which means that the load balancer has to use session stickiness to make sure the API is able to read the cookie correctly. 

Lets say you have:

* 1 Database
* You have 3 instances of Directus connected to this database
* 1 Load balancer

Enabling session stickiness on the load balancer level will make every request go to the same instance, negating the usefulness of having a load balanced setup in the first place. For normal CRUD operations, this isn't the end of the world, but it does become a problem for files. Generating / retrieving thumbnails is currently very heavy (see https://github.com/directus/api/issues/1542), which can result in load problems normally taken care of by the load balanced setup.

The user sessions are currently stored in the database, but for some reason the API is not able to work without the same `PHP_SESSID` also being present. This requires you to enable session stickiness, which in turn causes the problem mentioned above.

@bjgajjar Seeing we have the `directus-{project}-session` cookie which is managed through the database, is there anything we can do to drop the reliance on `PHP_SESSID` so it doesn't matter to what server you connect?

**Comment by rijkvanzanten** [comment]
Visual representation of the problem above:

![image](https://user-images.githubusercontent.com/9141017/70728195-f35cb000-1cce-11ea-93fe-3b835e2741b3.png)

Because the request is forced to follow the same path every time in order for the API to work properly, the first copy of Directus gets overloaded with requests from the app.

\* _The Directus App is technically not a separate instance, as it's returned by one of the three load balanced copies of Directus. It should be considered a separate entity from the moment the user has downloaded it into browser memory._

\*\* _The app in this example can be any project that connects using cookie mode._

**Comment by EnricoFerro** [comment]
Hi everybody,

I see another problem related. 

My problem is verified when a docker swarm is created and multiple instance is created. I suppose that this problem appends also in kubernes and in every situation with multiple instance or with serverless.

The cause of the problem is not caused by PHP_SESSID,  but  by the generation of directus-{project}-session cookie.

Actually for the generation of directus-{project}-session cookie is used a command `php_uname()` that is used for encrypt and decrypt the cookie. 
The result is a different key for the instances:
(Es:  Linux **546512a974cb** 4.15.0-76-generic 86-Ubuntu SMP Fri **Jan 17 17:24:28** UTC 2020 x86_64 - hostname and the hour of the machine could not be the same for every instance)

This information is not stable for all the machine. ( And is also not sure,  because is partially readable in /server/info  ).

I've prepared a merge that should resovle this problem.  
This solution change the logic of the cookie session generation using the auth.secret, an information that should be constant between the instances and an information that should be secret ( by definition ).

**Comment by rijkvanzanten** [comment]
Ah! Very good catch. That might actually be the cause of my initial problem 😄 

I was never able to fully verify if the PR that removes the PHPSESSID (#1582) solves the problem
