### ISSUE TITLE
Bug: Validation fails for numerical input with decimals

### ISSUE THREAD

**Issue by Pasukaru** [directus/api#1780]
Currently, the API returns an error  when entering a decimal (i.e: '1.21') into a numeric field, that's set to DECIMAL using DECIMAL as mysql datatype: 

![image](https://user-images.githubusercontent.com/1093680/75044481-ff7c9f00-54c1-11ea-95d6-4742e23e959a.png)

This is how I created the field:
![image](https://user-images.githubusercontent.com/1093680/75044420-e378fd80-54c1-11ea-820e-f1e8f39dbfe2.png)

I was able to reproduce this on the docker image **directus/directus:v8.2.0-apache** as well as in the demo account (https://demo.directus.io).

**Comment by hemratna** [comment]
As I can see from the given screenshot, you set length of Decimal datatype to `10,0`
You are trying to add value `1.21`
It will fail and show validation message because `10,0`  means a total of 10 digits precision and scale of `0`
Scale means digits after point(.).

Update length to `10,2` and try to add value `1.21`.
Let me know your feedback.

**Comment by hemratna** [comment]
This is the default behavior of MySQL.
We are closing this issue. 🙂

**Comment by ZiedHf** [comment]
Version : 8.8.1
I can't type : 
- 0
- 0.1
- 0.01
![image](https://user-images.githubusercontent.com/7974028/103191455-125ebd80-48a3-11eb-9d1e-cb1f106c95ce.png)
