### ISSUE TITLE
Expand EXIF and XMP metadata capabilities

### ISSUE THREAD

**Issue by asitemade4u** [directus/api#1813]
# Feature Request
Currently, as written in the doc, Directus scrapes uploaded images for EXIF title, location, tags (keywords), and description.
1. This is NOT what I see happening. I attach an image with a lot of EXIF metadata (including Description), and yet none is scraped.

![enchanted-vkz2nztfdrrr21-07-small](https://user-images.githubusercontent.com/11460106/77208581-7eb9be80-6ad2-11ea-8563-fc1c0a525529.jpg)

I also attach the metadata in the image, as output by EXIV2:
[metadata.txt](https://github.com/directus/directus/files/4361900/metadata.txt)

2. Now, is there a way to scrape MORE metadata, notably XMP -- which is widely used by asset management software such as **darktable** or **digikam**?

## What problem does this feature solve?
Use images themselves (and not XMP sidecar files) to convey information to the database, and ultimately to the Web publication (useful for copyright, captioning, etc.).

## How do you think this should be implemented?
By allowing developers to surcharge the relevant interface by adding new metadata key-value pairs.

**Comment by rijkvanzanten** [comment]
@WoLfulus 🔔 really important to get this right for api-next

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by asitemade4u** [comment]
I can help as I have based the whole website development (which was 
initially planned using WordPress) on the idea of saturating images with 
information upstream, then transferring it downstream to the database 
(there is a WP plugin for that).

**Comment by benhaynes** [comment]
Thanks @asitemade4u — and really good catch! I wonder what the overlap is between EXIF and IPTC metadata. To my knowledge, we scraped the latter.

In any event, we should be pulling as much information as possible from these sources automatically. We do have predefined fields for the key data, and I think adding the rest into the JSON metadata field (in Directus Files) might be a good option. Otherwise, we would need some sort of "mapping" system (or datatypes?) within Settings to map each value scraped to an individual field.
