### ISSUE TITLE
Some Core Type Changes should be allowed

### ISSUE THREAD

**Issue by asitemade4u** [directus/api#1814]
# Feature Request
For some reason (not required by the underlying SQL field definition), it is not allowed to change a field type to a yet compatible one (but that works sometime and sometime not):

- Text Area to Text Input (I have a collection where it is wholly forbidden)
- Radio button to Switch

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by benhaynes** [comment]
Seems like we could come up with a mapping of allowed datatype changes... but this should come with a BIG warning, since you may irreversibly truncate/delete data in doing so (eg: text -> varchar).

Also, there may be unidirectional ones, where we can go from **single** value datatypes to **multiple** value datatypes, but not the other way around.
