### ISSUE TITLE
Server error in creating a collection with name "advertising_xyz" or "advertisement_xyz"

### ISSUE THREAD

**Issue by ashx404** [directus/api#1879]
Version: 8.6.2 latest, 
Server: GCP CloudSQL, CloudRun for docker and Google Cloud storage bucket

Any collection starting with the name "advertising" or "advertisement_" results in a server error and then cannot be deleted from API. I had to manually drop the table from SQL. I am not sure this is done for any purpose. Had the same problem while creating it through API.
Can be also reproduced on https://demo.directus.io/
Just create a new collection with the name advertising or advertising_xyz  or advertisement_xyz and it will result in an error. 
Even if it is done for purpose, the delete functionality should work but it says "Trouble processing request. Try again after refreshing the page."

![image](https://user-images.githubusercontent.com/45964517/81183524-e4073780-8fcc-11ea-8348-3ca858e5a0ef.png)

![image](https://user-images.githubusercontent.com/45964517/81183592-f5504400-8fcc-11ea-8f1d-8c60e66eb860.png)

**Comment by benhaynes** [comment]
Hmm, I just followed your steps exactly and was able to create a collection called `advertising_sales` without issues. Also able to add fields and items to it successfully. Not sure what your'e doing differently, but I can assure you that there is no code that doesn't allow for "advertising_*" table names. 

Perhaps you have an odd keyboard layout that is using non-standard (latin) characters? Otherwise I would say it's a browser (or browser extension) issue and that you should tryin on a different machine.

![Screen Shot 2020-05-06 at 10 03 17 AM](https://user-images.githubusercontent.com/522079/81186658-0d01db00-8f81-11ea-9ea1-aa116240d3b2.png)

**Comment by ashx404** [comment]
Hey, Thanks. I retried it and actually figured why it was happening. It was my adblock blocking the keywords advertising and advertisement because the GET api had these keyword in it, so it was blocking it. Should have figured it earlier. Sorry

**Comment by benhaynes** [comment]
Sounds about right.
