### ISSUE TITLE
Add option to set API in read-only mode

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#22]
Adding a option to put the API in read-only mode, we lock all actions except reading data from the API.

We can aggressively cache the result as there's not change to be expected.

**Comment by danielfrentz** [comment]
How would this option be set? Is it an API call? a configuration option?

**Comment by rijkvanzanten** [comment]
Good question @danielfrentz.... It can be either a flag in `/config/api.php` or a flag in the directus_settings table. I'm not sure why yet, but I feel like this is something that I would expect to be in the php config file, but at the same time, it's also that you might want to enable / disable from the user interface, which makes it required to have in directus_settings 🤔 

What are your thoughts on this?

**Comment by danielfrentz** [comment]
I think it can be applied to both. use the configuration to set it initially and then allow the user to set it via the api.

**Comment by benhaynes** [comment]
I agree that the config makes the most sense, but we should really focus on moving _anything_ that needs to be updated after install to `directus_settings` so that it can be adjusted through the app/api. Not sure about having it in both – @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
Both is going to be confusing.. let’s put it in directus settings.

**Comment by computerwizjared** [comment]
@benhaynes @rijkvanzanten I was about to create a feature request for this, but then I saw there was already an issue for it. I have an odd use case for this feature- we are planning to run Directus 7 with multi-region redundancy on Amazon Aurora MySQL. As of right now, only read-only replicas are supported. Multi-master support is on the way, but it's not something we will want to pursue due to complexity. Since we will be hosting an instance of the API in two different regions for redundancy, we'd like to have the "master" region (with the writeable master database) host a writeable copy of Directus, while have the "slave" region (with the read-only replica) host a read-only copy of Directus. The only way to do this is through a config file setting, and not through the database, since the database contents must match in both the master and the replica.

Do you guys have any thoughts? Does my use case make sense? Thank you!

**Comment by rijkvanzanten** [comment]
@computerwizjared This makes total sense 🙂 It also means that `read-only` should be just that: no writing to directus_activity for logins or stuff like that either.

**Comment by computerwizjared** [comment]
@rijkvanzanten Wonderful!! For now, we'll continue down our path of upgrading to Directus 7 with multi-region support, regardless of this feature, since our application is read-only anyways. However, it would be awesome to be able to enforce this from the Directus API perspective so that we can be sure no writes will ever hit the replica database. If, in the future, we would need to write to the Directus API, we would put a direct endpoint to that instance in the "master" region.

Another possible idea that would work for our use case is to have a database endpoint in the config for a writer database, and another for a reader, so all reads would hit the reader database, and all writes would hit the writer (which would be located in the "master" region). This would probably be an idea for another ticket, though.

Let me know if you have any questions about our use case; I'd be happy to answer any. Thank you!

**Comment by rijkvanzanten** [comment]
> Another possible idea that would work for our use case is to have a database endpoint in the config for a writer database, and another for a reader, so all reads would hit the reader database, and all writes would hit the writer

I really like what you're suggesting here. We've been playing around with hosting Directus multi-tenant on a pretty big scale, and this could help out performance / prevent bottlenecks in a major way as well. @benhaynes 🔔

**Comment by benhaynes** [comment]
Ooh, I like that too. In my head I was imagining this setup as two "projects" (different databases), but many people will keep these in sync, so keeping it within the same project also makes sense. 👍

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
