### ISSUE TITLE
Add additional info to /

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#279]

**Comment by benhaynes** [comment]
Return:

* The supported thumbnail sizes
* The server timeout

**Comment by WellingGuzman** [comment]
Supported thumbnail are per instance, so it cannot be in the "home" endpoint.

**Comment by benhaynes** [comment]
Ahh, good point. @WellingGuzman can you think of any other useful server info to add to this endpoint?

And where can we add the thumbnail sizes?

**Comment by WellingGuzman** [comment]
I was thinking adding a "home" for instance, because I realize that information such as "timeout", "memory", "request body size" all those will eventually be configured per instance, so it will also makes sense to just use it on a new `instance`'s home endpoint.

While the `/` (home) endpoint will be using the global information while the `instance`'s home endpoint will be using the session information that will be applied using the directus settings.

What are you thoughts on this?

**Comment by benhaynes** [comment]
That makes sense to me... I like it!

Thoughts @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
`/` for global info
`/_/` for default env info
`/:environment/` for environment info

Makes sense to me 😄

**Comment by WellingGuzman** [comment]
When there's a new data we want to add into this ticket, lets create a new ticket.

`/` is the global  endpoint and `/:project_name` is the project endpoint.

**Comment by benhaynes** [comment]
@WellingGuzman have the items above been implemented? Eg: thumbnails, memory, timeout, etc
