### ISSUE TITLE
Files don't upload

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#291]
The file gets created with the correct name and extension, but remains empty (0 bytes) and has the mime type of `application/x-empty`. This is a problem only on my local machine, so it has to do with the specific setup..

```
<b>Notice</b>:  Undefined index: data in <b>/Users/rijkvanzanten/Development/api/src/core/Directus/Application/CoreServicesProvider.php</b> on line <b>276</b><br />
```

```
~/Development/app [master]
☛  apachectl -v
Server version: Apache/2.4.33 (Unix)
Server built:   Mar 22 2018 01:24:46
```

```
~/Development/app [master]
☛  php -v
PHP 7.1.16 (cli) (built: Mar 31 2018 02:59:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
``` 

```
~/Development/app [master]
☛  php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
exif
fileinfo
filter
ftp
gd
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

[Zend Modules]
```

**Comment by WellingGuzman** [comment]
The issue was triggered by having the `data` field on `directus_files` collection as an `alias`.

This is a expected behavior. All `alias` type are ignored. I still wonder if the user should be responsible for handling all the `alias` type they create. We created the `data` alias on `directus_fields`, shouldn't we be responsible to remove it before being inserted to the database after we are done using it?

It should work both ways, if you are responsible to add the `data` field before return it to the user, we should remove it after we done (via filter hook) which allows user to at least interact with the field if needed.

**Comment by rijkvanzanten** [comment]
This has been fixed by allowing data to be send to `alias` types
