### ISSUE TITLE
npm install fails on extensions

### ISSUE THREAD

**Issue by dur41d** [directus/api#321]
Getting error while installing extensions on freebsd. I tried many times.

## Version Info
  - Directus API version (Or commit hash):  c2ad961a9e041d6b65d7c9ef227741920d7bf407
  - PHP version:  7.2.8-nfsn1
  - MySQL version: n/a
  - Web server: (Ex. Apache, nginx or IIS?) n/a
  - OS name and version:  FreeBSD 11.1-RELEASE-p6
  - Node version: v8.11.3
  - NPM version: 6.3.0

## Expected Behavior

installation succeeds.

## Actual Behavior

getting error message: npm ERR! cb() never called!

## Steps to Reproduce
 1.  cd extensions
 2.  npm install
 3.  npm run build

## Schema Dump, Logs, or Screenshots

see attached output files for steps 2 & 3.

[npm_install_output.txt](https://github.com/directus/api/files/2287671/npm_install_output.txt)
[npm_run_build_output.txt](https://github.com/directus/api/files/2287674/npm_run_build_output.txt)

**Comment by benhaynes** [comment]
Thanks @dur41d – we'll get this sorted asap!

**Comment by rijkvanzanten** [comment]
Hey @dur41d! I'm not sure if this is a problem with our setup or `npm` itself.. 🤔 

`npm run build` fails because certain dependencies didn't get installed properly, so that's explainable

Based on a quick Google search, it seems like a bunch of people get the `cb() not called error` for a bunch of different reasons. Could you try updating npm and clearing your caches to make sure?

`npm cache clean -f` and `npm update` helps for some..

**Comment by rijkvanzanten** [comment]
I'm closing this as I'm suspecting is a personal config / npm issue and not specifically related to Directus
