### ISSUE TITLE
Comments Directus vs MySQL Schema

### ISSUE THREAD

**Issue by benhaynes** [directus/api#390]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Comments Directus vs MySQL Schema
### :+1: = 0
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
We can't solely use the MySQL column comments field because it's not supported in other DB types (SQLite, etc) so we need to keep it proprietary. But we can use the DB comments As the default comment if one is not saved in `directus_fields`

**Comment by rijkvanzanten** [comment]
We're currently saving and retrieving the ~column comments~ _field notes_ from the directus_* collections and don't rely on the database at all.

Seeing that every DB type will store comments in a separate way, and the fact that we don't have a way to _set_ the database-comments, I don't think it's worth it to implement using the DB comment as default. We can reopen and restart the discussion if anyone feels otherwise.
