### ISSUE TITLE
Activity is saving changes to directus_fields

### ISSUE THREAD

**Issue by benhaynes** [directus/api#466]
This is saving hundreds of items into activity when you re-order fields through Settings. This clogs up the activity page and will fill the database with GBs of unneeded data. 

Thoughts on what should be (or not be) included? @WellingGuzman @rijkvanzanten

![screen shot 2018-10-03 at 7 47 26 pm](https://user-images.githubusercontent.com/522079/46445506-3c1cee80-c745-11e8-8b43-02fbec489c53.png)

**Comment by WellingGuzman** [comment]
As this is an action by the application, in term of to the API it is just an update. Do we want the app to send `activity_skip=1` when its saving field sort update?

If the payload is only the `sort` field (any collection) we should ignore it. I do not like this one that much, because it's involve a lot of checking in the API side.

**Comment by rijkvanzanten** [comment]
I'll update the app to send `activity_skip` for re-sorting @WellingGuzman 🙂

**Comment by benhaynes** [comment]
Hey @rijkvanzanten – has this been done in the App? Let us know so we can close this...

**Comment by rijkvanzanten** [comment]
Yep!

https://github.com/directus/app/blob/7b29c9cf5be0c64ac3de93ba5c70a62644f5d67a/src/routes/settings/fields.vue#L449
