### ISSUE TITLE
File Uploads - Sub directories

### ISSUE THREAD

**Issue by bluesangria** [directus/api#509]
Hey all,

I've been trying to figure out a way to be able to upload files into subdirectories instead of everything to be under /uploads/_/originals/ because users are dumb. they won't know a file w the same name (logo.png for vendor1 is already there when trying to upload logo.png for vendor2). 

Anyhows, I finally made my way to CoreServicesProvider::getEmitter(). 

still not quite sure how to do it, gonna look at this function. I just posted this in case someone figured it out already. 

Thanks all :)

**Comment by benhaynes** [comment]
Hey @bluesangria – the duplicate file problem (#499) should be resolved tomorrow, would that help with this issue?

As for sub-directories, we were thinking about implementing virtual directories so files can be organized in the App and grouped in API responses... but I don't know if we'll be mirroring those virtual folders with real filesystem ones. That might be a nice feature to add in the future (mirroring virtual/actual folders) though... but I think we should have https://github.com/directus/app/issues/228 resolved before we start into that.

Thoughts?

**Comment by benhaynes** [comment]
I agree that actual directories would be a nice feature, but we would need a way for the UI to manage those first. I would certainly be down to discuss this further, but I feel like it will have to be a PR if you need it added in the short-term (our devs our pretty swamped). :)

**Comment by benhaynes** [comment]
I see actual _directories_ as a natural next step once we have _virtual_ folders. Whenever the user creates a folder in `directus_folders` we piggyback that event to also create a filesystem directory. Same thing happens when they move a file/folder into a folder... we move the actual file.

That part is easy and would only take a few extra hours to implement (once we have the virtual ones done). The trickier part is handling all of the exceptions (duplicate file names, how this works in different storage adapters, etc).

Either way, best of luck with your implementation... we'll follow up here once we have folders up-and-running!

**Comment by WellingGuzman** [comment]
I will leave this open as it was closed due to inactivity by the slate bot. It seems there's still some interest in this to be implemented.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
