### ISSUE TITLE
Relational tables permission issue - Public role

### ISSUE THREAD

**Issue by KPChakravarthy** [directus/api#544]
# Bug Report

## Steps to Reproduce

1. Create a collection
2. Add a `user` interface to the collection
3. Create an entry in the collection and select any user from the list.
4. Provide `Read` permissions for `Public` role to the collections `Directus Users` and `Relations`
5. Make API request for that collection without token

## Expected Behavior
Since there is a `read` permission, we should get the complete user details under `user`

## Actual Behavior
Returns only `id`

## Other Context & Screenshots
Same API call with Token returns a complete user data.

## Technical Details

- Device: Linux Shared Server
- OS: Linux
- Web Server: Apache 2.4.33
- PHP Version: 7.1.0
- Database: MySQL 5.5.61-38.13
- Install Method: cloned `master`

**Comment by WellingGuzman** [comment]
Hey @KPChakravarthy, this is an expected behavior. By default the API only fetches the first level of data, that's why you only see the `id`.

if you want to get the data of the `user`, you should use `fields` parameter.

Example: `/items/<collection>?fields=*,user.*`.

Read more about the fields parameter in the documentation: https://github.com/directus/docs/blob/master/api/reference.md#fields

**Comment by benhaynes** [comment]
I think he tried this @WellingGuzman – I had told him about that param on Slack. Maybe give it a try and see if it's working?

**Comment by WellingGuzman** [comment]
Now that I am seeing #543, it may be related to this. If it does I will keep this close in favor of #543
