### ISSUE TITLE
API saves ISO datetime wrong

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#563]
# Bug Report

If I send `1995-12-29T08:00+02:00` to the api, it saves `1995-12-29 08:00` disregarding the timezone.

**Comment by WellingGuzman** [comment]
The format in your example is missing the seconds. Unfortunately the API only supports on ISO date time format `1995-12-29T08:00:00+02:00`.

 Ideally will be great to support all date time formats.

The problem here is that we need to confirm is an ISO format before trying to convert them to UTC. It need to rethink how date time are save.

**Comment by benhaynes** [comment]
@rijkvanzanten – for now can we just have interfaces always submit with seconds?

**Comment by rijkvanzanten** [comment]
Ref https://github.com/directus/api/issues/536

**Comment by WellingGuzman** [comment]
This is actually not a bug, but a feature request to support more ISO formats, rather than just `1995-12-29T08:00:00+02:00`. For example, without minutes or minutes and seconds.

**Comment by WellingGuzman** [comment]
There's three format supported all include full date and time.

Example:
```
Using time offset
2019-01-04T16:12:05+00:00

Ussing Z
2019-01-04T16:12:05Z

Using Z without Dashes
20190104T161205Z
```

Implemented by https://github.com/directus/api/commit/93a0dfac2a698e8251085e651df82d83847f00be
