### ISSUE TITLE
Incorrect URLs in emails sent from API

### ISSUE THREAD

**Issue by Nitwel** [directus/api#597]
When requesting a password reset, the link directs to localhost and not to the api url.
I guess the image is also not showing because of that.

![grafik](https://user-images.githubusercontent.com/22577866/48676858-e2de1280-eb6c-11e8-9c83-10dedebe22e8.png)

Directus 2.0.8

**Comment by alioygur** [comment]
@WellingGuzman we all waiting for you, where are you? :)

**Comment by benhaynes** [comment]
It might be the path, or the logo might be missing too... either way let's also make sure that we're using the newest logo. I can provide it if needed...

**Comment by Nitwel** [comment]
As I said XD

**Comment by WellingGuzman** [comment]
The password reset url are based on the `project_url` setting in `directus_settings`.

Fixing this https://github.com/directus/api/issues/502#issuecomment-434207321 issue was making this value hard default to `http://localhost`.

This should be improved to try to guess the url based on the request.

**Comment by Nitwel** [comment]
Also, #609 is related to the mail having wrong links ^^.

**Comment by WellingGuzman** [comment]
The problem with the logo is that the link to the `getdirectus.com` is broken.

I am going to fallback to the url based on the request instead of `http://localhost` that should solve this issue. If for some reason that's not the public-facing url of your project, you can set the `project_url` settings in the API (can be done in Admin Settings on the application).

**Comment by WellingGuzman** [comment]
The API has not field for `project_url`, so you probably can't se this through the app Admin Settings.

But in `directus_settings` you can add a new item with `key=project_url` and set the value to your public facing url.

```
POST /<project>/settings

{
  "key": "project_url",
  "value": "https://my-domain.tld"
}
```

Otherwise it will fallback to the url based on the HTTP Request (guessing your url), the same way it guesses the uploaded files full URLs.

The Logo url has been updated to `https://directus.io/img/assets/directus-white.png`.

The URLs should be working as expected now. Otherwise let us know and we will reopen this ticket to address any issues with the new implementation.

**Comment by benhaynes** [comment]
@WellingGuzman @rijkvanzanten — would it make sense to include this as a global setting in the App so it can be adjusted more easily?

**Comment by WellingGuzman** [comment]
@benhaynes I believe so, the option is there so it would make sense to add that field to the settings page.

I open a ticket for this: https://github.com/directus/api/issues/670

**Comment by WellingGuzman** [comment]
I added the field to to Directus Settings Fields.

I added that missing field the bottom of the form. I wonder if that looks ok, or should it be moved to the top, along with the `project_name` field (missing).

So it looks like this:

```
[ Project Name Input]
[ Project URL Input]
[ Logo Input]
[ Color Input]
[ Trusted Proxies Input]
[ Auto Sign Out]
```

If we want to have this conversation we could talk about otherwise, the field has been added by https://github.com/directus/api/commit/4f82d08d0186622617518258a0c93c09a77c7ef2.

**Comment by benhaynes** [comment]
Gotcha. @rijkvanzanten — can we add this field into the App?

**Comment by WellingGuzman** [comment]
@benhaynes I don't know if @rijkvanzanten has to do anything on the app side, but I need to add those fields in the migrations files in the API side.

**Comment by benhaynes** [comment]
Oh, I thought you said it was already added. 😕 

I'll re-open... but let's get this added (if it isn't already) and call it done!

**Comment by WellingGuzman** [comment]
oh no, I added the `project_url`, which fixes this ticket.

I was referring to add the missing `project_name` and reorder the fields. (a new discussion)

**Comment by benhaynes** [comment]
👍 

https://github.com/directus/api/issues/676
