### ISSUE TITLE
Cannot create a user nor a role

### ISSUE THREAD

**Issue by sebj54** [directus/api#634]
# Bug Report

## Steps to Reproduce

1. Go to Settings → Roles or Users
2. Click on the "plus" button
3. For a role, just fill a name and hit "save"
4. For a user, fill required fields and hit "save"

## Expected Behavior

Role or user should be created

## Actual Behavior

An error is shown in the console

## Other Context & Screenshots

Error message:

```json
{
  "code": -2,
  "message": "API returned invalid JSON",
  "error": {},
  "data": "<br />\n<b>Fatal error</b>:  Call to undefined function Ramsey\\Uuid\\Generator\\random_bytes() in <b>/home/ltcreati/api-emile-weber/vendor/ramsey/uuid/src/Generator/RandomBytesGenerator.php</b> on line <b>35</b><br />\n"
}
```

## Technical Details

- Device: Desktop
- OS: Windows 10
- Browser: Firefox
- Directus App: 7.0.10
- Directus API: latest
- Install Method: cloned directus/directus@master

**Comment by sebj54** [comment]
@rijkvanzanten Thanks, it fixed the problem! 👍 
I didn't know fatal errors were "development warnings" though 😂

**Comment by rijkvanzanten** [comment]
haha yeah fair, it's just annoying that PHP will append an HTML element for the error/warning which in turn breaks the app since it's expecting JSON 🙄

**Comment by WellingGuzman** [comment]
`random_bytes` is only available in php 7, and not in php 5. You installed Directus from the `directus/directus` repository that seems to have downloaded all dependencies using php 7, while you are using php 5, and that's why you are seeing the error.

On the other hand there's a open ticket to address this issue with the api and php injecting errors and warning to the response here: https://github.com/directus/api/issues/438

I will close this ticket, and anything related to php injecting warnings/errors should go to the previous ticket.
