### ISSUE TITLE
Add email endpoints

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#65]
We need a generic way to send emails to users;

could be something like `/_/email/:id` where ID would be the user where it's send too. The user has to provide the title, subject, body copy,.. ?

**Comment by benhaynes** [comment]
I don't think we should limit this system to Directus users, if you have an app users collection and want to dynamically send email then this could be really useful. Also, since we will have email templates as another modular extension, admins could add in app styled templates for their own purposes.

So if we all agree on this, then we would remove the `:id` and add the standard header fields: `to`, `cc`, `bcc`... and also add a param for template (which defaults to the Directus style).

Thoughts? @WellingGuzman @rijkvanzanten

**Comment by rijkvanzanten** [comment]
Ah, yeah that makes sense. Do you also want to think of some useful parameters to make it easier to send emails to specific users / groups? `group: 2` or `user: 15`

**Comment by benhaynes** [comment]
Good idea! Yeah, we should have User, Group, and All for shortcuts.
