### ISSUE TITLE
File endpoints aren't working

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#67]
For example `/thumbnail/200/200/crop/good/filename.jpg` returns 

```
{
    "error": {
        "error": 8,
        "message": "API Environment Configuration Not Found: 200"
    }
}
```

or `/storage/uploads/filename.jpg` returns 

```
{
    "error": {
        "error": 8,
        "message": "API Environment Configuration Not Found: storage"
    }
}

**Comment by WellingGuzman** [comment]
where do you have the api directory set up? I am aware of the thumbnailer not working, but the storage should be working.

Are you using apache?

**Comment by rijkvanzanten** [comment]
This is local apache without any changes to the config

**Comment by WellingGuzman** [comment]
What's do you get on `/files` endpoint as `full_url/url`? also what's your filesystem configuration?

**Comment by WellingGuzman** [comment]
We were talking about moving `/<width>/<height>/<filename>` to `<width>x<height>/<filename>`, that way the dimension parameter is one and the directory for each thumbnail is one based on the dimension (`100x150`) instead being one directory for `100` and a subdirectory for `150`.

A question raised about the result dimension being different if the `contain` option was used instead of `crop` when the image doesn't have a 1:1 aspect ratio. Which create a image with different size that one which was sent.

Currently the directories are created based on the url parameters instead of the result of the image. This is a good way for catching the url based on the request instead of the results parameters.

Quality and Fit option are optional but these options won't make any different as it won't conflict with other options, as many qualities and fit can be saved, but the sizes have to be unique.

Having a `100x100` and `100x150` can conflict if the request file for `100x150` with `contain` result in a image `100x100` which is the actual size but the content may be different.

The benefits of having one `100x100`:
- Makes it one parameter instead of two
- Easier to walk over the directories

Any thoughts?

**Comment by WellingGuzman** [comment]
The thumbnailer has been implemented and the settings are now on `directus_settings`

Read the options here: https://github.com/directus/api/wiki/Thumbnail
