### ISSUE TITLE
Add ability to delete projects

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#689]
# Feature Request

We can already create projects through the API, however, there's no way to remove one this way.

## What problem does this feature solve?

Right now, you can programmatically generate more projects on the fly. However, you can't delete them.

**Comment by rijkvanzanten** [comment]
It has to reverse everything the create project does: remove the config file and clear the database

**Comment by rijkvanzanten** [comment]
Only admin accounts in the default `_` project have the ability to remove projects.

**Comment by WellingGuzman** [comment]
Things about deleting projects (As we agreed on):

- Admin from any projects are allowed to delete projects.
- the default project is required deleting the default project won't allow any admin to delete any projects. In other word the API will be in a "not installed properly" state.
- We want to restrict who can delete projects, and not requiring the default project to be configured in order to delete other projects or do not allow to delete the default project if there's others projects created.

Ref: https://github.com/directus/api/commit/0978286f186c1227b5810fb85f6c470b287c943d
