### ISSUE TITLE
Add status parameter to "Get Item Revisions" endpoint

### ISSUE THREAD

**Issue by KKAries** [directus/api#695]
# Bug Report

## Steps to Reproduce

The doc says that the get item revisions api support query parameter status but it seems not work.

1. Create an item with status field. 
2. Update item status so it has a few revisions.
3. Use api GET /[project]/items/[collection-name]/[id]/revisions?status=draft to get the revisions
4. See the response have those published status revisions.

## Expected Behavior
The return revisions only contain draft status revisions.
## Actual Behavior
Return everything.
## Technical Details

Using directus api 2.0.13.

**Comment by benhaynes** [comment]
Not sure if this is an enhancement or a bug — but I'll let @WellingGuzman decide!

**Comment by rijkvanzanten** [comment]
[Docs say it should work like this](https://docs.directus.io/api/reference.html#status), it doesn't, so it's a bug 🐛

**Comment by WellingGuzman** [comment]
It's not actually a bug, but something in between, the correct docs reference is this one [Get Revisions](https://docs.directus.io/api/reference.html#get-item-revisions), although it says works with `status`, it wasn't meant to. The revisions table doesn't have a status field, and each revision is a JSON string in the `delta` column, which mean, it can be easily query using SQL.

There's JSON support since MySQL `5.7.8`, but this needs to be abstracted for other database, so this need a bit more thinking if want to properly implement this.

**Comment by benhaynes** [comment]
> which mean, it can be easily query using SQL

I think you meant _can't be easily queried..._ 😉

**Comment by benhaynes** [comment]
So I can think of three options:

1. Use MySQL to search the JSON (requires `5.7.8+`)
2. Add a column to activity to track `status`
3. Remove this query feature

Thoughts @WellingGuzman @rijkvanzanten ?

**Comment by KKAries** [comment]
What I am trying to do is to get the latest published revision data. It would be good to support status in get revisions api so that I don't need to iterate every revision one by one.

**Comment by WellingGuzman** [comment]
@KKAries At the moment, there's no way to filter the revision data based on the delta (or any JSON field).

So far what we could do if support JSON queries if the DB supports it, but we need to think in a way on doing the abstraction (at least slightly, so it will be easier to support future db implementation).

> So I can think of three options:
> 
> 1. Use MySQL to search the JSON (requires `5.7.8+`)

I like this one.

> 2. Add a column to activity to track `status`

No a good option, because this won't work for any other field change, and only be used if the collection has a status field.

> 3. Remove this query feature

The non-supported params doesn't throw any error, so this is a expected behavior, nothing to remove here.

**Comment by rijkvanzanten** [comment]
Number 1 is the only suitable option realistically.

Do we have any knowledge on what versions of MySQL people actually use? I noticed Google's Cloud platform only offering 5.6 and 5.7, but there's already a MySQL `8.x`? I imagine having to write an abstraction for MySQL pre-5.7 would result in quite a heavy program right? Having to fetch all the rows, then search through them in PHP.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
