### ISSUE TITLE
API logs expected "errors"

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#699]
# Bug Report

When a user error happens, the API still logs it to a file.

## Steps to Reproduce

1. Try logging in with the wrong password
2. See error.log created

## Expected Behavior

The API should only log unexpected "errors" (eg system failures instead of user errors)

## Actual Behavior

The API logs all non-200 status requests

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by pzehle** [comment]
Hello, I guess this just was never fixed because in one project I am still using v8 and this is getting really big. I requested assitance on Discord but no comment, so I think this would be the best place for this.

I have a websocket in my project that is constantly calling the API to retrieve some information, this runs every second for each user. The project only has 10 users at the moment, and this is what happens now:

When the websocket opens connection, it retrieves information from the database, returns it and syncs it, this is ok. Though in my project it doesn't really matter if there is data or not, but for Directus, when it finds data it returns it, but when it doesn't find data, returns a 404 error (this is ok!). But after the 404, a log is added, and this is not (as you know) a 1-liner with the error, this is the big slim log just to say it didn't find any data.

For 10 users, 1 second per day, my every-day log file weights over 2gb, which is making my project crash everyday due to no memory issues.

Question, how can I resolve this? I commented the line for 'logger' in the config file, but no lock, logs are still being created. Hope you can help me, as this is killing me, my project and everyone around me xD

Thanks!

**Comment by rijkvanzanten** [comment]
I don't know if there was a configuration in v8 to disable this (hence this being a feature request).. I think your best bet here is to either setup a cronjob to delete those logs every X minutes, or find the logic within the api that creates those log files, and disable it there 👍🏻

**Comment by pzehle** [comment]
Thank you. So far I have checked most of the files and I cannot find the one that saves the logs. I guess I just have to keep checking. Thanks anyway.
