### ISSUE TITLE
Add PATCH /projects endpoint

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#716]
# Feature Request

Add the ability to update the config dynamically through the API.

## What problem does this feature solve?

You're able to set certain config properties when creating a project (like cors), although, there's no way to change them after a project has been created.

## How do you think this should be implemented?

I think the only thing the API can do using the current implementation of `php` based config files is overwrite the whole file using the new config options. Ideally, it should read the existing config file's config array, replace the values, and overwrite the file.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by benhaynes** [comment]
@rijkvanzanten @wolfulus — is this related to the config PR changes for Docker?

**Comment by WoLfulus** [comment]
This probably needs a better engineering. This would require a full refactor of how configs are handled, and might conflict with docker deployments (which are ephemeral).

I already thought about this on #930 and that's why I abstracted the configuration into different loaders. So for example we can configure only the base information (db) through env/file, and other settings comes from an external source (redis, consul, ...) and gets cached to avoid performance penalties.

**Comment by benhaynes** [comment]
Seems like a good direction! We'll review that PR as soon as you give us the _go-ahead_!

**Comment by WoLfulus** [comment]
I'll get back to it tonight. Haven't had enough time yesterday
