### ISSUE TITLE
Can't properly query nested fields on "Files" field

### ISSUE THREAD

**Issue by Kinzi** [directus/api#729]
# Bug Report

I have a collections with a *file* field `featured_image`and a *files* field `images`.

If I query the table with `?fields=featured_image.filename,featured_image.title,images.image.filename,images.image.title`

it return only the last field from images (so filename in this case). The other gets ignored.
For the featured image both values get returned:

```
{
    "data": [
        {
            "featured_image": {
                "filename": "visita-tour-sintra-desde-lisboa-palacio-pena.jpg",
                "title": "visita tour sintra desde lisboa palacio pena"
            },
            "images": [
                {
                    "image": {
                        "title": "castelo dos moros castillo de los moros"
                    }
                },
[...]
```
## Steps to Reproduce

1. Set up collection with a files field
2. Upload some images
3. Query for several fields in `images.image`

**Comment by romaiiinnn** [comment]
Hi,
Do we know if this issue has been resolved ? I am getting the same behavior. In my example : 
http://localhost:8000/_/items/event/1?fields=contents.images.image.id,contents.images.image.archive_number

is only returning the "archive_number" field, the last field requested.

If requesting : 
http://localhost:8000/_/items/event/1?fields=contents.images.image.archive_number,contents.images.image.id
is only returning the "id" field... the last field requested.

We can only get all the fields by requesting ?fields=contents.images.image.*

Thanks

**Comment by benhaynes** [comment]
Hey @romaiiinnn — we can look into this if you can send over a sql dump of your setup. If it's private you can send over Slack:

https://directus.chat

**Comment by romaiiinnn** [comment]
Hi @benhaynes ,
I don't feel confortable sharing the database I'm working on as this is not my data. Though, you can reproduce the bug using the Demo API. The issue seems to happen when there is a many-to-many relation table containing a directus_files field. For example, in the demo API, the members collection has a field "favorites" which is a M2M with the movies. If you try to access the poster field from the movie, you'll have the same issue :

This query returns only the id poster id (no filename field returned):
https://demo-api.directus.app/_/items/members/1093?fields=favorites.movie.poster.filename,favorites.movie.poster.id

This query returns only the filename field (no id returned) : 
https://demo-api.directus.app/_/items/members/1093?fields=favorites.movie.poster.id,favorites.movie.poster.filename

**Comment by benhaynes** [comment]
That's completely understandable! Thank you for confirming it happens on the demo and steps to reproduce it.

We'll give it a try!

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1260
