### ISSUE TITLE
Filter on O2M and M2M not working

### ISSUE THREAD

**Issue by benhaynes** [directus/api#784]
It's saying `Unable to find field "movie"` which makes sense since it's an ALIAS.

```
https://next.demo-api.directus.app/_/items/members?fields=*.*.*&filter[favorites.movie][has]=1
```

@WellingGuzman can you write docs on how this should be done? Or, if it's not working, why.

**Comment by WellingGuzman** [comment]
The issue here was that `movie` is not a field of `o2m` type. That's why it throws the following error:

```
Unable to find field "movie"
```

Ideally this should throw an error saying the field is not a O2M field, or something more clear.

The request should have as below:

```
https://next.demo-api.directus.app/_/items/members?fields=*.*.*&filter[favorites][has]=1
```

At the moment it doesn't work because there's a bug with `has` creating an incorrect query. See: https://github.com/directus/api/issues/576

**Comment by rijkvanzanten** [comment]
@benhaynes Based on @WellingGuzman's last response, I feel like this issue is actually not an issue with filters, but instead an issue with a wrong record on the demo database?

**Comment by benhaynes** [comment]
Seems that way! Should we leave this open to clarify the error or close it?

**Comment by rijkvanzanten** [comment]
I think we can close it, as the original issue isn't an issue

**Comment by RuslanZavacky** [comment]
@rijkvanzanten I was following this issue as we had the same happened to completely clean database...

**Comment by benhaynes** [comment]
@RuslanZavacky — is your issue because of `has`?

**Comment by pikzelz** [comment]
@rijkvanzanten I am also trying to get the filter to work with a M2M relation, however it is giving me an unexpected error.

I have a table **trains** and a table **stations**, I link them together with a junction table called trains_stations with fields: train and station.

In the setup of M2M (stations on the trains table) I link **trains.id** to **trains_stations.train** and **stations.id** to **trains_stations.station**

When I specify my filter like: `/trains?filter[stations][all]=1` 

I get an error: `Failed generating the SQL query. Statement could not be executed (42000 - 1066 - Not unique table/alias: 'trains')`

With query: ```SELECT `trains`.`active` AS `active`, `trains`.`id` AS `id`, `trains`.`name` AS `name` FROM `trains` WHERE `trains`.`id` IN (SELECT `trains`.`years` AS `years` FROM `trains` RIGHT JOIN `trains` ON `trains`.`id` = `trains`.`years` WHERE `trains`.`id` IN ('1') GROUP BY `trains`.`station` HAVING COUNT(*) = '1') AND `trains`.`active` IN ('published') AND ((`trains`.`active` = 'published')) ORDER BY `trains`.`id` ASC LIMIT 200 OFFSET 0```

Shouldn't it be looking in the junction table or the stations table? As the default trains table doesn't hold a **station** column. Or am I not understanding it correctly?

Whenever I specify it like `/trains?filter[stations][eq]=1`

I get the expected error: `Failed generating the SQL query. Statement could not be executed (42S22 - 1054 - Unknown column 'trains.station' in 'where clause')`

**Comment by benhaynes** [comment]
@rijkvanzanten is mostly on the App side — but maybe @bjgajjar has some thoughts?

**Comment by pikzelz** [comment]
@benhaynes thanks. @bjgajjar I've been going down the path further and it looks like it keep repeating the original table in the relation functions instead of the junction table it needs to set in the relation to be able to get it to work. I tried to get it to work myself but haven't been able to (mainly because I don't have enough time to spend on it). Hopefully this is helpful.

**Comment by bjgajjar** [comment]
@pikzelz Thanks for the pointing out. I will check the issue ASAP. :)
