### ISSUE TITLE
Not respecting sort column for sorting by default

### ISSUE THREAD

**Issue by computerwizjared** [directus/api#811]
# Bug Report

## Steps to Reproduce

1. Create a table with a few rows.
2. Add some values to the table.
2. Create a sort column on the table.
3. Re-order the table's rows.
4. The API automatically returns a sort with the ID, rather than the "sort". Explicitly specifying "?sort=sort" forces it to sort by the sort value.

## Expected Behavior

The API should always use the "sort" column by default, and not the "id" column for sorting.

## Actual Behavior

Even if a "sort" column is present, Directus uses the "id" column to sort.

## Technical Details

Directus Docker 7.0.17

**Comment by rijkvanzanten** [comment]
@benhaynes Not too sure if this is a bug or an enhancement 🤔 

While it makes sense from a theoretical standpoint to sort by the `sort` field by default, it was never designed nor implemented that way.

**Comment by computerwizjared** [comment]
@rijkvanzanten Understood if that is the case, however it took us a bit to realize that functionality changed from v6.

**Comment by benhaynes** [comment]
Hmm, I agree that this is a noticeable difference from v6 (and we should call that out in the Docs). But I also agree with what Rijk mentioned. At first, it does make sense to order by `sort` by default, _but_ I'm not sure about adding a new field changing the data response order... and what if we wanted two sort fields (not even sure how that would work). 

I guess it's good to make these things as explicit as possible — so it makes sense to order data by `pk` unless you say otherwise. This is a subjective gray-area... so we'll just have to make a call. Let's leave this open for a while to gather community input and then we'll make a call. For now let's keep it as an enhancement.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
