### ISSUE TITLE
File upload with base64 doesn't work

### ISSUE THREAD

**Issue by dur41d** [directus/api#835]
# Bug Report

File upload via Base64 return 400 'bad request'. Following the instructions here:

https://docs.directus.io/api/reference.html#using-base64-content

## Steps to Reproduce

Execute the python code. Make sure you put 'picture.jpeg' file in the script path.

```python
import requests
import json
import base64


with open('picture.jpeg', "rb") as f:
	data = base64.b64encode(f.read()).decode('utf-8')
	payload = {};
	payload['filename'] = f'picture.jpeg'
	payload['data'] = data
	jsonPayload = json.dumps(payload)
	response = requests.post('https://<apibase>/public/_/files?access_token=<your token>', data = jsonPayload)

```

## Expected Behavior

Response should be 200. 

## Actual Behavior

Response is 400.

## Technical Details
- API version: 2.0.19
- Device: Desktop
- OS: Windows 10
- Python: 3.6.3

**Comment by syslogic** [comment]
@dur41d `base64.b64encode(f.read())` should already suffice, while `.decode('utf-8')` might not be required, or this might even be the cause for the upload operation to fail (unless also setting content-type headers). I'm not certain about this, unless having managed to reproduce the issue, but it appears to be one possible culprit. Could you please try once without the `.decode('utf-8')` instruction and report back?

**Comment by dur41d** [comment]
You're right. This code works:

```python
import requests
import json
import base64


with open('picture.jpeg', "rb") as f:
    data = base64.b64encode(f.read())  # .decode('utf-8')
    payload = {}
    payload['filename'] = f'picture.jpeg'
    payload['data'] = data
    # jsonPayload = json.dumps(payload)
    response = requests.post('https://<apibase>/api/public/_/files?access_token=<token>', data = payload)

```

Regarding changing the root, i'm using a shared host so I can't do that. We discussed this at length in
https://github.com/directus/api/issues/636

I'm closing this issue.

**Comment by benhaynes** [comment]
@dur41d and @syslogic — would adding anything to the Docs help others avoid this issue?

**Comment by syslogic** [comment]
@dur41d even on a shared hosting, this should be possible, at least while the control-panel permits setting the web-root on a per-domain or a per-subdomain basis (access to this capability may vary from provider to provider). I've already seen this feature request (which is about setting it to another location than `/` or `public/` ) and was thinking about aliasing the location; this also seems rather hosting-configuration related, than it would be directly related to whatever script being deployed there. I would have to create a test-install once, to see if it affects the functionality.

@benhaynes working code-examples in the most common languages might be the best possible support (or example client implementations, which utilize the existing SDK libraries). because ordinary, when knowing how the output shall look alike, this is something one can produce - however, this might still require some trial & error to get there... that's why proven to be working examples would provide a good reference - and example clients would provide starting-points for custom development.

**Comment by benhaynes** [comment]
That's a great point @syslogic — we're working through a few priority tickets at the moment, but after that we'll definitely focus more on example code in the Docs (and example code repos). 👍

**Comment by dur41d** [comment]
@syslogic I'm using [nearlyfreespeed.net](https://www.nearlyfreespeech.net/) and I don't see that I can change the document root. But in any case I don't want to because I want to use the same site for the `api`, `app` and the frontend website and not a separate site for each. I think the api path being hard-coded to `public` is inflexible and not necessary and does not play well with shared hosts.
