### ISSUE TITLE
Permission Denied on Directus Fields Endpoint

### ISSUE THREAD

**Issue by Pujan789556** [directus/api#923]
# Bug Report

## Steps to Reproduce

1) Go to Roles & Permissions and Click **Public**
2) Toggle Show Directus System Collections
3) Click All on  **Fields**

## Expected Behavior
- Able to get **Fields** of any collections with endpoint  **<project_key>/fields/[collection]**

## Actual Behavior
- Got **{"error":{"code":3,"message":"Permission denied"}}**

## Technical Details

- Device: Desktop
- OS: Ubuntu 18.04
- Browser: Chrome
- Directus App: 7.2.0
- Install Method:  cloned `master` branch of `directus/directus`

**Comment by benhaynes** [comment]
I'm assuming that the App is saving the proper permissions in the database (could you confirm this @Pujan789556 ?) so I've transferred this to the API repo.

My guess is that `directus_fields` has a relationship with another collection that you haven't given permission to. Could you also try giving _all_ Directus system collections public read permission to see if the error persists?

**Comment by Pujan789556** [comment]
![Screenshot from 2019-04-29 17-05-29](https://user-images.githubusercontent.com/10183860/56972341-89055e00-6b8a-11e9-8320-cd5934c92379.png)

**Comment by Pujan789556** [comment]
Give ALL permission on each Directus System Collection. But not working.

**Comment by benhaynes** [comment]
Thank you for checking!

Do you see all of these permissions being saved to the database in `directus_permissions`?

**Comment by bjgajjar** [comment]
@benhaynes 

Actually, as per the current code, there is a specific condition that only admin can access the `field` related API. When the user updates the permission of `fields` as publically accessible, It stored in DB successfully but because of this condition, the user is not able to get the response. So I think we should remove this condition to make them accessible as per the permission.

**Comment by Pujan789556** [comment]
@benhaynes  @bjgajjar  all permission is saved in database but not reflected in api as mentioned by @bjgajjar

**Comment by benhaynes** [comment]
Interesting. OK, so usually if there is an explicit conditional in the code it's because we added it to solve some other problem. Before we remove the _admin-only_ conditional, can we think of any reason why we would want to protect that Fields information from `READ`?

Any hints in the code, @bjgajjar ?

🔔 @rijkvanzanten

**Comment by benhaynes** [comment]
The only reason I can think of is that some users have limited access to fields (some fields might be hidden for them) and this endpoint would tell them _all_ the fields. But, this read permission is off by default, so if an admin turns it on they should know what they're doing. So I can't think of any reason why `READ` should always be disabled for normal users.

Here is the Field Object we're talking about:
https://docs.directus.io/api/reference.html#field-object

**Comment by bjgajjar** [comment]
@benhaynes 

We need to add the condition which can give access based on the permission which is set. Right now it is accessible by `admin` only. I'll implement the needful changes and send the PR ASAP.

**Comment by bjgajjar** [comment]
Fixed in #980
